### ISSUE TITLE
Old Twitter Logo needs to be fixed.

### ISSUE THREAD

**Issue by xiaoyaoyaowww** [sapondanaisriwan/old-twitter-logo#1]
The ico of the twitter website has now been replaced by x and needs to be fixed!

https://abs.twimg.com/favicons/twitter.3.ico -> https://abs.twimg.com/favicons/twitter.2.ico

**Comment by sapondanaisriwan** [comment]
It seems to be impossible to fix it using CSS alone.

**Comment by sapondanaisriwan** [comment]
please install user script instead: https://greasyfork.org/en/scripts/471687-old-twitter-logo

**Comment by xiaoyaoyaowww** [comment]
> please install user script instead: https://greasyfork.org/en/scripts/471687-old-twitter-logo

Thanks,it work well.
